/**:
  ros__parameters:
    # 0: PS4    1: Thrustmaster
    joystick_type: 0

    # can ids
    base_yaw_id: 5

    shoulder_pitch_id: 10

    elbow_pitch_id: 4

    wrist_pitch_id: 6

    wrist_roll_id: 7

    #additional parameters
    fast_mode_multiplier: 10