# Copyright (c) 20224 Stogl Robotics Consulting UG (haftungsbeschr√§nkt)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Source of this file are templates in
# [RosTeamWorkspace](https://github.com/StoglRobotics/ros_team_workspace) repository.
#

swerve_drive_controller:
  state_joints: {
    type: string_array,
    default_value: [],
    description: "(optional) Specifies joints for reading states. This parameter is only relevant when state joints are different then command joint, i.e., when a following controller is used.",
    read_only: true,
    validation: {
      unique<>: null,
    }
  }
  front_left_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front left drive joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  front_right_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front right drive joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  rear_left_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear left drive joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  rear_right_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear right drive joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  front_left_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front left swerve joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  front_right_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front right swerve joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  rear_left_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear left swerve joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  rear_right_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear right swerve joints used by the controller.",
    read_only: true,
    validation: {
      unique<>: null,
      not_empty<>: null,
    }
  }
  track_width: {
    type: double,
    default_value: 0.6604,
    description: "Specifies track width, or the distance in meters between left and right wheel for calculation purposes. ",
    read_only: true,
    validation: {
      not_empty<>: null,
    }
  }
  wheelbase: {
    type: double,
    default_value: 0.8382,
    description: "Specifies wheelbase, or the distance in meters between front and back wheels for calculation purposes. ",
    read_only: true,
    validation: {
      not_empty<>: null,
    }
  }
  wheel_radius: {
    type: double,
    default_value: 0.254,
    description: "Specifies wheel radius calculation purposes. ",
    read_only: true,
    validation: {
      not_empty<>: null,
    }
  }