# Default initial positions for athena_arm's ros2_control fake system

initial_positions:
  actuator: 0
  base_yaw: 0
  elbow_pitch: 0
  gripper_claw: 0
  shoulder_pitch: 0
  wrist_pitch: 0
  wrist_roll: 0