teleop_twist_joy:
  ros__parameters:
    enable_button: 0
    
    axis_linear.x: 1        # up/down
    axis_linear.y: 2        # left/right
    axis_linear.z: -1

    # unsure why but ackermann controller only goes about half this speed
    scale_linear.x: 1.27
    scale_linear.y: 0.0
    scale_linear.z: 0.0

    axis_angular.yaw: 0        # rotate
    axis_angular.pitch: -1
    axis_angular.roll: -1

    # ackermann controller turns to at max scale_angular.yaw*pi. Seems to ignore how much you input, relies on how fast rover is going
    scale_angular.yaw: 0.5
    scale_angular.pitch: 0.0
    scale_angular.roll: 0.0
    publish_stamped_twist: true