teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1 #TODO: Fix
      y: 0 #TODO: fix
    scale_linear:
      x: 0.5 #TODO: make match speed
      y: 0.5
    scale_linear_turbo:
      x: 1.0
      y: 1.0
    
    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0
    
    enable_button: 4 # TODO: fix
    enable_turbo_button: 5 #TODO: Fix